config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: :show
  resources :reviews 
  resources :comments
  root 'reviews#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def new
        @comment = Comment.new
    end
    
    def create
        Comment.create(commemt_params)
    end
    
    
    private
        def commemt_params
            params.require(:comment).permit(:commemt, :rate, :nickname)
        end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    def index
        @reviews = Review.all
    end
    
    def new
        @review=Review.new 
    end
    
    def create
        Review.create(review_params)
    end
    
    def show
        @review = Review.find(params[:id])
    end
    
    def edit
        @review = Review.find(params[:id])
    end
    
    
    private
    def review_params
        params.require(:review).permit(:image, :text, :title, :rate)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h3>
      投稿が完了しました。
 </h3>
 <a class="btn" href="/reviews">投稿一覧へ戻る</a>

app/views/comments/new.html.erb
<%= form_for(@comment) do |f| %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
    <%= f.label :comment %>
    <%= f.text_field :comment %><br>
    <%= f.label :rate %>
    <%= f.number_field :rate, placeholder:'評価' , value: 1, max: 10, min: 1 %>
    <%= f.submit "送信する" %>
<% end %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header  class="header">
      <div class="header_logo" >
        <h1><a>Collection</a>         
          <% if user_signed_in? %>
            <div class="nav">
              <ul class="nav_name">
              <%= link_to "マイページ","/users/#{current_user.id}" %>
              <%= link_to "ログアウトする", destroy_user_session_path, method: :delete %>
              <%= link_to "投稿する", "/reviews/new" %>
             </ul>
            </div>
          <% else %>
            <div class="nav">
             <ul class="nav_name">
          
              <%= link_to "ログイン", new_user_session_path %>
              <%= link_to "新規登録", new_user_registration_path %>
            
             </ul>
            </div>
          <% end %>
          </h1>
      </div>
    <%= yield %>
  </body>
</html>

app/views/reviews/create.html.erb
 <h3>
      投稿が完了しました。
 </h3>
 <a class="btn" href="/reviews">投稿一覧へ戻る</a>
 

app/views/reviews/index.html.erb
<div class = "contents">
 <div class = "cocntent">
  <% @reviews.each do |review| %>
    <div class = "content_image">
     <p><%= image_tag "#{review.image}" %></p>
    </div>
    <div class = "cocntent_text">
     <p><%= review.title %></p>
    </div>
    <div class = "content_review">
     <p><%= link_to 'このレビューをみる', review_path(review.id), method: :get %></p>
    </div>
  <% end %>
   </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%= form_for(@review)  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :text %>
  <%= f.text_area :text %><br>
  <%= f.file_field :image %><br>
  <%= f.label :'評価' %>
  <%= f.number_field :rate, placeholder:'評価', value: 1, max: 10, min: 1 %><br>
  <%= f.submit "送信する" %>
  
    <% end %>
    
    

app/views/reviews/show.html.erb
<div>
    <div class = "content_show">
        <div class = "content_show_image">
            <%= image_tag "#{@review.image}" %>
        </div>
        <div class = "content_show_title">
            <%= simple_format(@review.title) %>
        </div>
        <div class = "content_show_text">
            <%= simple_format(@review.text) %>
        </div>
    </div>
    
    <%= link_to "コメントを投稿する", "/comments/new" %>

</div>

app/views/users/show.html.erb
<div>
    <div>
        <h2><%= current_user.email %><span>さんのマイページ</span></h2>
             <% @reviews.each do |review| %>
            <div class = "content_image">
                 <p><%= image_tag "#{review.image}" %></p>
            </div>
            <div class = "cocntent_text">
             <p><%= review.title %></p>
            </div>
            
          <% end %>
        <%= link_to "レビューを投稿する", "/reviews/new" %>
        <%= link_to "コメントを投稿する", "/comments/new" %>
        
    </div>
    
</div>

 